## Python NumPy random module
    Using the NumPy random module, we can generate random integers, floating-point numbers, random samples from distributions, and shuffled arrays efficiently. It is faster and more powerful than Python’s built-in random module when working with large datasets and numerical computations.
    
    The random module is available through numpy.random, which includes many useful functions such as rand(), randint(), choice(), permutation(), and seed() to generate and control randomness.

In [1]:
import numpy as np
import random

In [2]:
rd_num = np.random.random(1)
rd_2d_array = np.random.random((3,3))
print (rd_num)
print (rd_2d_array)

[0.75408823]
[[0.41953032 0.61398507 0.57449873]
 [0.8133237  0.16040224 0.4428432 ]
 [0.01339112 0.51311079 0.15002104]]


### np.random.randint()

In [3]:
rd_no = np.random.random(1)
rd_2D_arr = np.random.randint(1,4, (4,4)) 
rd_3D_arr = np.random.randint(1,4, (2,4,4)) 
print (rd_no)
print (rd_2D_arr)
print (rd_3D_arr)

[0.69635504]
[[2 1 3 2]
 [1 2 2 3]
 [1 3 3 1]
 [1 2 3 3]]
[[[3 1 2 3]
  [3 3 3 1]
  [2 1 2 1]
  [1 2 2 2]]

 [[2 2 3 3]
  [3 3 2 3]
  [1 1 2 1]
  [2 2 2 2]]]


### np.random.seed()

In [4]:
np.random.seed(10) 
rd_3D_arr = np.random.randint(1,4, (2,4,4)) 
print(rd_3D_arr)

[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


### np.random.rand()

In [5]:
arr_2D = np.random.rand(3,3) 
print(arr_2D)

[[0.13145815 0.41366737 0.77872881]
 [0.58390137 0.18263144 0.82608225]
 [0.10540183 0.28357668 0.06556327]]


### np.random.randn()

In [6]:
arr_2D = np.random.randn(3,3) 
print(arr_2D)

[[ 0.67893119 -1.91355421 -0.94245806]
 [-1.74554298 -1.02094527 -0.16206903]
 [-0.6579709   0.42211306  0.62402334]]


### np.random.choice() 

In [7]:
x = [1,2,3,4] 
choice_from_x = np.random.choice(x)  
print(choice_from_x ) 

1


In [8]:
for i in range(15): 
    print(np.random.choice(x)) 

1
3
1
3
3
1
4
2
1
4
2
3
3
2
3


### np.random.permutation() 

In [9]:
x_permute = np.random.permutation(x) 
print(x_permute)

[2 4 1 3]
