### Numpy Mathematical Functions
    In Numpy,  Mathematical FunctionsNumPy provides a wide range of mathematical functions such as arithmetic operations, trigonometric functions, exponential functions, logarithmic functions, and statistical calculations. These functions help perform complex calculations easily without writing long loops in Python.
    
    Using NumPy mathematical functions improves performance, readability, and efficiency when working with large datasets in data analysis, machine learning, and scientific computing.

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]



### Addition of Two Numpy Array 

In [3]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### Subtraction of Two NumPy Array

In [5]:
arr1 - arr2


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Division of Two NumPy Array

In [7]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Multiplication of Two NumPy Array

In [9]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
np.multiply(arr1 , arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### Matrix Product of Two NumPy Array (matrix)


In [11]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [12]:
arr1.dot(arr2)


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### NumPy Mathematical Built-in functions

#### 1. np.max()

In [13]:
arr1.max()

np.int64(9)

In [14]:
arr1.max(axis = 0)

array([7, 8, 9])

In [15]:
arr1.max(axis = 1)

array([3, 6, 9])

#### 2. np.argmax()

In [16]:
arr1.argmax()

np.int64(8)

#### 3. np.min()

In [17]:
arr1.min()

np.int64(1)

In [18]:
arr1.min(axis = 0)

array([1, 2, 3])

#### 4. np.argmin()

In [19]:
arr1.argmin()

np.int64(0)

#### 5. np.sum()

In [20]:
np.sum(arr1)

np.int64(45)

In [21]:
np.sum(arr1, axis = 0)

array([12, 15, 18])

In [22]:
np.sum(arr1, axis = 1)

array([ 6, 15, 24])

#### 6. np.mean()

In [23]:
np.mean(arr1)

np.float64(5.0)

#### 7. np.sqrt()

In [24]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

#### 8. np.std() - Return standerd division of Numpy array

In [25]:
np.std(arr1)

np.float64(2.581988897471611)

#### 9. np.exp() - Return exponential value 

In [26]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

#### 10. np.log() - Return natural log of each element

In [27]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [28]:
np.log10 (arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])