#  Numpy 
    NumPy (Numerical Python) is a powerful open-source Python library used for numerical computing and working with large, multi-dimensional arrays and matrices efficiently.

    It provides:
    
    - Fast mathematical operations
    - Multi-dimensional array object (ndarray)
    - Built-in mathematical and statistical functions
    - Broadcasting for efficient computations
    - Support for linear algebra operations

## Basic of Numpy - Mathematic samples

In [57]:
a = 9 
b = 8
print (a*b)
print (a - b)
print (a**3)
print (a + b)
print (a/b)
b**3


72
1
729
17
1.125


512

## importing Library of NumPy

In [4]:
import numpy as np

In [5]:
# sample of suppoting function
np.min([4,2,7,4])

np.int64(2)

####  full array Documentation  

In [54]:
np.array([5,2,8,1,9])

array([5, 2, 8, 1, 9])

####  Assign in Variable/ Object

In [8]:
list = np.array([5,2,8,1,9])

In [9]:
list

array([5, 2, 8, 1, 9])

In [10]:
print(list)

[5 2 8 1 9]


## Dimesional Array

###  1. One Dimesional Array

In [12]:
oneD_array = np.array([1,2,3,4,5])

In [13]:
oneD_array

array([1, 2, 3, 4, 5])

### 2. Two Dimesional Array

In [15]:
twoD_array = np.array([[1,2,3],
         [4,5,6],
         [7,8,9],
         [3,6,9]])

In [16]:
twoD_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 6, 9]])

### 3. Three Dimesional Array

In [18]:
threeD_array = np.array([[[1,2,3],[4,5,6]],
         [[4,5,6],[7,8,9]],
         [[1,2,3],[7,8,9]]])

In [19]:
threeD_array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [7, 8, 9]]])

## Check the Dimension  - ndim()

In [21]:
threeD_array.ndim

3

In [22]:
oneD_array.ndim

1

### Shape of Array  -  shape

In [24]:
threeD_array.shape   # (3,2,3) - 3 - dim (axis)  |  2 - row  |  3 - cols

(3, 2, 3)

In [25]:
twoD_array.shape

(4, 3)

In [26]:
print("Number of Rows:",twoD_array.shape[0])
print("Number of Cols:",twoD_array.shape[1])

Number of Rows: 4
Number of Cols: 3


###  Test and Check twoD_array

In [28]:
twoD_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 6, 9]])

### Find the type of array  -  type()

In [30]:
type(twoD_array)

numpy.ndarray

In [31]:
type(threeD_array)

numpy.ndarray

### Check the size of array

In [33]:
threeD_array.size

18

In [34]:
threeD_array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [7, 8, 9]]])

### Change the DataType of array

In [36]:
threeD_array = np.array([[[1,2,3],[4,5,6]],
         [[4,5,6],[7,8,9]],
         [[1,2,3],[7,8,9]]],dtype = float)

In [37]:
threeD_array

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[4., 5., 6.],
        [7., 8., 9.]],

       [[1., 2., 3.],
        [7., 8., 9.]]])

## Create metrics using python NumPy functions  - Numpy ones () function

In [56]:
np.ones((4,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Create metrics using python NumPy functions  - Numpy zeros () function

In [41]:
np.zeros((4,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Create metrics using python NumPy functions  - Numpy empty () function

In [43]:
np.empty((4,3))

array([[8.54265507e-312, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 9.70157962e+189, 6.82116729e-043],
       [7.17330383e-091, 2.95066456e+179, 1.55196357e+184],
       [5.15724391e-062, 6.48224659e+170, 4.93432906e+257]])

### Create NumPy 1D array using arange() function 

In [44]:
arr = np.arange(1,59)

In [45]:
print (arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58]


## Create NumPy 1D array using linspace() function

In [47]:
np.linspace(1,7,9)

array([1.  , 1.75, 2.5 , 3.25, 4.  , 4.75, 5.5 , 6.25, 7.  ])

### Convert 1D array to multidimensional array using reshape() function

In [49]:
arange_1 = np.arange(1,13)
arange_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
 np.reshape(arange_1, shape=(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Convert multidimensional array in one dimensional - flatten()

In [53]:
import numpy as np 

arr_name = np.array([[1,2,3],[4,5,6,]])
array_name = arr_name.ravel()
print("Using ravel :",array_name)



Using ravel : [1 2 3 4 5 6]


In [ ]:
import numpy as np
arr_name = np.array([[1,2,3],[4,5,6,]])
array_name = arr_name.flatten()
print("Using flatten :",array_name)

 ### Transpose metrics 

In [ ]:
arr_name = np.array([[1,2,3],[4,5,6,]])
arr_name.T