## Python NumPy array shape Function

    In NumPy, provides the shape function to check the dimensions of an array. It tells us how many rows, columns, or axes an array has.
    Shape means the structure of the array.

In [1]:
import numpy as np

#### The shape of a NumPy 1D array

In [2]:
arr_1D = np.array([1, 2, 3])
print("One dimensional NumPy Array : \n",arr_1D)
shape_of_arr_1D = np.shape(arr_1D)
print("Shape of arr_1D = ",shape_of_arr_1D)

One dimensional NumPy Array : 
 [1 2 3]
Shape of arr_1D =  (3,)


#### The shape of a Numpy 2D array 

In [3]:
arr_2D = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print("One dimensional NumPy Array : \n",arr_2D)
shape_of_arr_2D = np.shape(arr_2D)
print("Shape of arr_2D = ",shape_of_arr_2D)

One dimensional NumPy Array : 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Shape of arr_2D =  (3, 3)


#### The shape of a Numpy 3D array

In [4]:
arr_3D = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], 
[1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print ("Three dimensional NumPy Array : \n",arr_3D)
shape_of_arr_3D = np.shape(arr_3D)
print("Shape of arr_3D = ", shape_of_arr_3D)

Three dimensional NumPy Array : 
 [[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
Shape of arr_3D =  (3, 3, 3)


#### Python NumPy array shape using shape attribute

In [5]:
np.shape
shape_of_arr_1D = arr_1D.shape
print("Shape of 1D array =", shape_of_arr_1D)

Shape of 1D array = (3,)


#### Python NumPy array shape vs size

In [6]:
student_info = np.array([['id', 'name', 'percentage', 'pass or fail'],  
                     [101, 'Ajay', 80, 'pass'],  
                     [102, 'John', 75, 'pass'], 
                     [103, 'Abraham',33, 'fail'], 
                     [104, 'Oprah',52, 'pass'] 
                    ]) 
shape_of_student = np.shape(student_info)
print("Shape of studcent information array = ", shape_of_student)

Shape of studcent information array =  (5, 4)
