## Python Numpy Array concatenation and split
    NumPy provides powerful functions to combine (concatenate) multiple arrays and divide (split) arrays into smaller parts. These operations are very useful in data processing, machine learning, and numerical analysis when handling large datasets.

In [1]:
import numpy as np


In [2]:
arr1 = np.arange(1,17).reshape(4,4)
print (arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
arr2 = np.arange(17,33).reshape(4,4)
print (arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


### Concatenate list1 and list2

In [4]:
list1 = [2,4,6,7]
list2 = [1,8,3,5]
list1 + list2

[2, 4, 6, 7, 1, 8, 3, 5]

### Concatenate of arr1 and arr2

In [5]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [6]:
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


###  Concatenate array row wise using axis attribute 

In [7]:
np.concatenate((arr1,arr2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

###  Vertical order concatenate in arrays

In [8]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

###  Horizontal order concatenate in arrays 

In [9]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [10]:
np.hstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

### Break the Array using Split() method

In [11]:
np.split(arr1, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

####  Check the array data type after using split() function

In [12]:
list1 = np.split(arr1, 2)
type(list1)

list

In [13]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
type(list[0])

types.GenericAlias

### Array row wise split

In [15]:
np.split(arr1, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

###  Split 1D array in user requirement  

In [16]:
A1 = np.array([4,7,1,3,9])
np.split(A1, [1,3])

[array([4]), array([7, 1]), array([3, 9])]